# Generated by Django 4.0.5 on 2022-10-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tip',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_round', to='tips.round'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_team', to='tips.team'),
        ),
    ]
