# Generated by Django 4.0.5 on 2022-10-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_alter_season_year_alter_tip_round_alter_tip_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.DateField(verbose_name='year'),
        ),
    ]
