# Generated by Django 4.1.3 on 2022-11-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_alter_season_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
