# Generated by Django 4.1.3 on 2022-11-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_alter_team_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fav_team',
            field=models.ForeignKey(blank=True, null='', on_delete=django.db.models.deletion.CASCADE, related_name='favourite_team', to='tips.team'),
        ),
    ]
