# Generated by Django 4.1.3 on 2022-11-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0008_alter_team_logo_url_alter_team_name'),
        ('accounts', '0002_alter_customuser_fav_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fav_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite_team', to='tips.team'),
        ),
    ]
